services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lms-system'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: